### ISSUE TITLE
Version_gen.h missing

### ISSUE THREAD

**Issue by thomasantony** [atenart/dtc#1]
When trying to build this, I get the error:
```
mak	 CC util.o
e cutil.c:37:25: fatal error: version_gen.h: No such file or directory
 #include "version_gen.h"
                         ^
compilation terminated.
heck
Makefile:255: recipe for target 'util.o' failed
make: *** [util.o] Error 1
chip@chip:~/dev/iot/dtc$ make check
	 CC tests/testutils.o
	 CC util.o
util.c:37:25: fatal error: version_gen.h: No such file or directory
 #include "version_gen.h"
                         ^
compilation terminated.
Makefile:255: recipe for target 'util.o' failed
make: *** [util.o] Error 1
```

Unless I create a new `version_gen.h` file defining the constant DTC_VERSION as a valid value. 

Something like:
```
#define DTC_VERSION "DTC 1.4.2-gee8a9269"
```

**Comment by atenart** [comment]
Hi,

This repository only is a mirror, with some patches applied to make use of DTC's overlay. I do not maintain it neither add any feature or fix.

Have a look at the official sources instead :)

**Comment by thomasantony** [comment]
@atenart I was linked here by http://stevencombs.com/chip/2016/08/14/chip-and-led.html#install-the-python-gpio-library

I was thinking maybe this was a fork for that platform. Thanks anyway.
